### ISSUE TITLE
About Chinese datasets

### ISSUE THREAD

**Issue by BearRedy** [princeton-nlp/PURE#1]
Can this code deal with chinese text please?

**Comment by a3616001** [comment]
We trained and evaluated our models on English datasets, and our released models can only handle English.

However, you can definitely train your own models on the other datasets or in other languages using our code. To do so, besides converting the dataset into the format described in the repo, you need to add labels of the dataset in `shared/const.py` and add the dataset into the argument `--task` in `run_entity.py` and `run_relation.py`.

If your data is in Chinese, you may want to use a pre-trained language model that supports Chinese (e.g., `bert-base-multilingual-uncased`).

Hope this helps!

**Comment by BearRedy** [comment]
> We trained and evaluated our models on English datasets, and our released models can only handle English.
> 
> However, you can definitely train your own models on the other datasets or in other languages using our code. To do so, besides converting the dataset into the format described in the repo, you need to add labels of the dataset in `shared/const.py` and add the dataset into the argument `--task` in `run_entity.py` and `run_relation.py`.
> 
> If your data is in Chinese, you may want to use a pre-trained language model that supports Chinese (e.g., `bert-base-multilingual-uncased`).
> 
> Hope this helps!

thanks a lot!

**Comment by YaoXinZhi** [comment]
Great job. So, if I change these codes, will I be able to use your code on any data set of the same task ?

**Comment by a3616001** [comment]
@YaoXinZhi  Yes, the code should work on other datasets of the entity-relation extraction task.

**Comment by nlper01** [comment]
> Can this code deal with chinese text please?

大佬，你好，我在跑对比实验，能否分享一份可以在中文数据集上跑通的代码以及几条数据示例（好用chatgpt快速完成数据格式转换），我的邮箱是2674053421@qq.com，感激不尽！
