### ISSUE TITLE
How to compute the REL+ F1(strict)

### ISSUE THREAD

**Issue by YeDeming** [princeton-nlp/PURE#10]
Hi Zexuan,

Is there any script for computing the REL+(strict), which mesures the correction of entity type and relation prediction.

In the run_relation.py,  the output f1 seems to be REL F1.

Best,
Deming

**Comment by a3616001** [comment]
Hi Deming,

Yes. Please check [run_eval.py](https://github.com/princeton-nlp/PURE/blob/main/run_eval.py).

You can run the evaluation script to output the end-to-end performance (Ent, Rel, and Rel+) of the predictions.
```
python run_eval.py --prediction_file {path to output_dir}/predictions.json
```

Best,
Zexuan

**Comment by YeDeming** [comment]
Thanks!
