### ISSUE TITLE
Negative sampling

### ISSUE THREAD

**Issue by pauloamed** [princeton-nlp/PURE#13]
Hey! Once again, great work!

Since I don't have enough computer resources for experimenting myself, I need to address this question to you guys.

Have you tried sampling the negative samples (non-ner spans) instead of taking them all? 
If so, did it yield good results? 
If it didn't, do you have a clue why not?

Thanks in advance!

**Comment by a3616001** [comment]
For the entity task, we didn't try to sample negative samples, as taking all samples won't hurt the efficiency too much. 

For the relation task, in our preliminary experiments, we tried only sampling a subset of negative pairs such that we have the same number of negatives and positives. Doing so slightly hurts the final performance. Two possible reasons: (1) by doing sub-sampling, we lose training signals; (2) it causes a discrepancy between training and testing (i.e., the distribution of negatives shifts).

Hope this helps!

**Comment by pauloamed** [comment]
It helped! Thanks!
