### ISSUE TITLE
Error about running run_entity.py on SciERC

### ISSUE THREAD

**Issue by HuiStudent** [princeton-nlp/PURE#16]
Error1:  OSError: Model name 'allenai/scibert_scivocab_uncased' was not found in tokenizers model name list.....

So I upgrade some dependency packages (torch=1.8.1, transformers=4.6.1). But I find a new error.

Error2: TypeError: Caught TypeError in replica 0 on device 0. 
            TypeError: dropout(): argument 'input' (position 1) must be Tensor, not str

I hope you can help me. what are the dependency packages when you run run_entity.py on SciERC?

**Comment by a3616001** [comment]
Hi, could you install dependencies specified in [requirement.txt](https://github.com/princeton-nlp/PURE/blob/main/requirements.txt)?
