### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'scierc_models/ent-scib-ctx0/ent_pred_dev.json'

### ISSUE THREAD

**Issue by appledora** [princeton-nlp/PURE#17]
Hello,
I keep getting the error mentioned on the title while running this script :
```
python run_relation.py   --task scierc   --do_train --train_file scierc_data/processed_data/json/train.json   --do_eval --eval_with_gold   --model  allenai/scibert_scivocab_uncased   --do_lower_case   --train_batch_size 8   --eval_batch_size 32   --learning_rate 2e-5   --num_train_epochs 3   --context_window 100   --max_seq_length 128    --entity_output_dir scierc_models/ent-scib-ctx0   --output_dir scierc_outputs
```
I have also tried with `--eval_test` argument and without using either `--eval_test` and `--eval_with_gold`, both throw the same error.  
Earlier I had managed to run the first two evaluation scripts provided with the repo, seamlessly. They produced `ent_pred_test.json` and `predictions.json`, respectively and as expected. : 
 ```
# Run the pre-trained entity model, the result will be stored in ${scierc_ent_model}/ent_pred_test.json
python run_entity.py \
    --do_eval --eval_test \
    --context_window 0 \
    --task scierc \
    --data_dir ${scierc_dataset} \
    --model allenai/scibert_scivocab_uncased \
    --output_dir ${scierc_ent_model}

# Run the pre-trained full relation model
python run_relation.py \
  --task scierc \
  --do_eval --eval_test \
  --model allenai/scibert_scivocab_uncased \
  --do_lower_case \
  --context_window 0\
  --max_seq_length 128 \
  --entity_output_dir ${scierc_ent_model} \
  --output_dir ${scierc_rel_model}
```
Could you please tell me if I am doing anything wrong?

**Comment by a3616001** [comment]
Hi!

`ent_pred_dev.json` is the prediction file returned by the entity model on the **dev set**. To generate it, you need to run the entity model **without** `--eval_test`.

For example,
```bash
python run_entity.py \
   --do_eval \
   --context_window 0 \
   --task scierc \
   --data_dir ${scierc_dataset} \
   --model allenai/scibert_scivocab_uncased \
   --output_dir ${scierc_ent_model}
```

Let me know if there is still an issue!

**Comment by appledora** [comment]
I was also thinking about doing this. Thanks for the clarification :) 
However, I am still confused about why a previous evaluation output file is required for the training task? Isn't evaluation done after training? Especially curious because I am trying to adapt the relation extraction model for the `Bengali` language. In that case, where do I get the evaluation `ent_pred_dev.json`?  Should I first run the `run_entity.py` model with the `--do_train` argument and then run again with the `--do_eval` argument to obtain the `json`? 
Please, forgive me if my questions are a bit naive. Thanks! 
ps: would really appreciate an issue or discussion on the pipeline of adapting this interesting work for other languages other than `English`.

**Comment by a3616001** [comment]
We need `ent_pred_dev.json` during training because we need to evaluate the model on the dev set for model selection. 
In our default setting, we use the predicted entities for model selection. This is why we run `run_entity.py` here to generate the prediction file.

If you want to do model selection based on the gold entities instead of the predicted entities, you can just use your gold `.json` file of dev set as `ent_pred_dev.json` and train the model with `--eval_with_gold`.

So to adapt the relation model on your dataset. You can either train an entity model first and run the entity model with `--do_eval` to obtain the `ent_pred_dev.json`; or you can just use the original gold `.json` file you have (copy and rename it as `ent_pred_dev.json`).

**Comment by appledora** [comment]
Thanks a lot! This has been helpful.
