### ISSUE TITLE
About Multiple Entity Pairs in the Same Sentence

### ISSUE THREAD

**Issue by HaishuoFang** [princeton-nlp/PURE#2]
Hello,

For multiple entity pairs in one sentence,  do you separately generate a new sentence for each entity pair during training? How do you sample negative samples? I mean entity pairs without relations

Thank you

**Comment by HaishuoFang** [comment]
Another question: do you consider the directionality of 'hyponym of' in scierc?

**Comment by a3616001** [comment]
Hi Haishuo,

> For multiple entity pairs in one sentence, do you separately generate a new sentence for each entity pair during training? How do you sample negative samples? I mean entity pairs without relations

Yes, we generate a training instance for each entity pair. Suppose there are n entities in a sentence, we will generate n*(n-1) instances. We didn't downsample negatives and used all of them among those n*(n-1) pairs.

> do you consider the directionality of 'hyponym of' in scierc?

Yes. We simply considered all relation types as asymmetric relations in our implementation.

**Comment by HaishuoFang** [comment]
Thank you for your reply! How do you implement it?  I didn't find the code of creating two different labels. For example, creating two different labels: hyponym of(S, O) and hyponym(O, S)?  I guess you process them when generating data?
Just let the latter entity to be subject and the former one to be object

**Comment by a3616001** [comment]
We didn't create two different labels for a relation. For example, for a relational triple (S, hyponym of, O), the label of (S, O) will be "hyponym of" and (O, S) will be "no relation". Creating directional labels for a relation type may bring benefits, but we didn't test that.
You can refer to [this code](https://github.com/princeton-nlp/PURE/blob/main/relation/utils.py#L21) for converting entity data to relation data.

**Comment by HaishuoFang** [comment]
I got you! Thank you
