### ISSUE TITLE
Question about ACE2004

### ISSUE THREAD

**Issue by SihengLi99** [princeton-nlp/PURE#21]
Hello,

This work is very interesting! 
However, I can not find the code about how you do the k-fold cross-validation in ACE2004.

Siheng

**Comment by a3616001** [comment]
Hi Siheng,

Thanks for your interest!
We follow [DyGIE's script](https://github.com/luanyi/DyGIE/tree/master/preprocessing) to process the ACE04 dataset. The split can be found [here](https://github.com/luanyi/DyGIE/tree/master/preprocessing/ace2004/split).

Best,
Zexuan

**Comment by SihengLi99** [comment]
Sincerely thank you!

Have a good day!

**Comment by syuoni** [comment]
Hi, 

Given the cross-validation, are the scores reported on ACE04 averaged over the five folds? Thanks

**Comment by a3616001** [comment]
@syuoni Yes, the numbers on ACE04 are averaged over five folds.
