### ISSUE TITLE
tool to create training data 

### ISSUE THREAD

**Issue by AlanQuille** [princeton-nlp/PURE#22]
Hello,
I was wondering, how do you create the custom training data in JSONL format? Do you do it manually or do you have access to a tool? Thank you very much.

**Comment by a3616001** [comment]
Hi Alan,

For ACE04/ACE05, we use the [DYGIE's script](https://github.com/luanyi/DyGIE/tree/master/preprocessing) to convert the raw data in JSONL format.
For SciERC, the processed JSONL file can be downloaded in their [website](http://nlp.cs.washington.edu/sciIE/).

For other datasets, it should be easy to write a python script and dump the dataset in a JSONL file (e.g., using `json.dump`).

Best,
Zexuan

**Comment by AlanQuille** [comment]
Thank you very much for your prompt reply.
