### ISSUE TITLE
 --do_train --train_file {path to the training json file of the dataset} \

### ISSUE THREAD

**Issue by AlanQuille** [princeton-nlp/PURE#23]
Hi,
I was wondering what specifically is referred to by --train_file? Is it the JSONL file used as the input file for the entity model? Thank you very much.

**Comment by a3616001** [comment]
Yes, `--train_file` specifies the JSONL file of the training set and it is the input file for the entity model.

**Comment by AlanQuille** [comment]
Thank you very much. Is it also the same file for where it says --train_file in the Approximation relation model section?

**Comment by a3616001** [comment]
Yes, it is the same file that is used in the approximation model.

**Comment by AlanQuille** [comment]
Great, thank you very much.
