### ISSUE TITLE
Creating custom dataset from scratch

### ISSUE THREAD

**Issue by appledora** [princeton-nlp/PURE#27]
I was wondering if you download the training data, in original `sciERC` format [(as shown here)](http://lavis.cs.hs-rm.de/storage/spert/public/datasets/scierc/scierc_train.json) and then reformat again `automatically` internally before training the model? Asking this, because a little confused whether to **format my custom dataset like sciERC or your input data format, as shown on the `Readme.md`** . Also, sciERC annotates sentence wise , as per the aforementioned link. How does pure handle multisentence passages?  The pretrained models that are downloaded by the repo-provided `Readme.md` link, are also labeled as `single sentence model`.

**Comment by a3616001** [comment]
Hi, we downloaded the processed SciERC ([link](http://nlp.cs.washington.edu/sciIE/data/sciERC_processed.tar.gz)), which is in the same format as shown on the README.

In our experiments, we do not consider cross-sentence relations. All the datasets (ACE04, ACE05, SciERC) are annotated in the sentence level. So we consider each sentence individually if there are multiple in a passage. For cross-sentence relations, you can concatenate sentences and apply our approach on concatenated inputs to predict cross-sentence relations.

**Comment by appledora** [comment]
Sort of a complementary question, the processed dataset has an additional `clusters` node for each document. What does it refer to or is it important?

**Comment by serenalotreck** [comment]
I think those are coreference clusters, as the model that SciERC was created for also incorporates coreference resolution. I believe this pipeline doesn't do that, so they probably aren't used?

**Comment by a3616001** [comment]
The `clusters` field contains the coreference annotations. Our approach doesn't use those annotations, so you may ignore this field when using our code.
