### ISSUE TITLE
KeyError causing custom training to halt

### ISSUE THREAD

**Issue by AlanQuille** [princeton-nlp/PURE#31]
Hello,
I believe I have resolved my previous issue with the custom training. I have to wait 10 minutes to move on from "Waiting for CUDA..." but it does successfully move on to the next stage. However, I get the following error:

File "run_entity.py", line 197, in <module>
	dev_samples, dev_ner = convert_data_to_samples(dev_data, args.max_span_length, ner_label2id=ner_label2id, context_window=args.context_window)
File "/home/programmer/Documents/data/custom_triples_phases/PURE/entity/utils.py", line 122, in convert_dataset_to_samples
	sample['spans_label'].append(ner_label2id[sent_ner[(i,j)]])
KeyError: 'LOC'

Do you have any idea what is causing this error? Just as a reminder, my train, dev and test JSON files are as follows (with different doc_keys):

{"clusters": [], "doc_key": "Test_001", "sentences": [["Google", "was", "founded", "on", "September", "4", ",", "1998", ",", "by", "Larry", "Page", "and", "Sergey", "Brin", "while", "they", "were", "Ph.D", ".", "students", "at", "Stanford", "University", "in", "California", "."], ["On", "December", "3", ",", "2019", ",", "Pichai", "also", "became", "the", "CEO", "of", "Google", "."], ["In", "March", "1999", ",", "the", "Google", "moved", "its", "offices", "to", "Palo", "Alto", ",", "California", "."]], "ner": [[[0, 0, "ORG"], [10, 11, "PER"], [13, 14, "PER"]], [[33, 33, "PER"], [39, 39, "ORG"]], [[46, 46, "ORG"], [51, 54, "LOC"]]], "relations": [[[0, 0, 10, 11, "Founder"], [0, 0, 13, 14, "Founder"]], [[33, 33, 39, 39, "CEO"]], [[46, 46, 51, 54, "Located in"]]]}

The command I ran is as follows:

python run_entity.py --do_train --learning_rate=1e-5 --task_learning_rate=5e-4 --train_batch_size=16 --context_window 0 --data_dir data_dir --model bert-base-uncased --output_dir output_dir --task inception

Thank you very much.

**Comment by a3616001** [comment]
Hi, did you write all possible entity types ('ORG', 'PER', 'LOC', etc) in `shared/const.py`? It seems that you define a new task `inception`, but `LOC` is not a valid entity type defined in `shared/const.py`.

**Comment by AlanQuille** [comment]
I believe I did, I will double check tomorrow.

**Comment by AlanQuille** [comment]
You are right, const.py did not have 'LOC' defined for 'inception'. It was a mistake on my end, I had two const.py files for two systems but I ran the code on the system which did not have 'LOC' defined. I will run the code again tonight but I am confident it will work. Thank you very much for your help.
