### ISSUE TITLE
What is the command to do predictions after training a custom model?

### ISSUE THREAD

**Issue by AlanQuille** [princeton-nlp/PURE#33]
I have successfully trained a model using custom data. Now I want to input a document and have the model predict the relations in the document. What is the command to accomplish this? Thank you very much.

**Comment by a3616001** [comment]
Hi! You can use `--do_eval` to run the trained model. If you want to run the model on unlabeled data, the easiest way for you to do this might be to create a empty "ner" and "relations" field in your dataset and still run the model with `--do_eval`. See #30 .

**Comment by AlanQuille** [comment]
Thanks for the reply.  By "dataset" do you mean the dev.json or test.json? Also, would the command look something like this:


python run_relation.py \
  --task inception \
  --do_eval --eval_test \
  --model bert_base_uncased \
  --do_lower_case \
  --context_window 0\
  --max_seq_length 128 \
  --entity_output_dir ${scierc_ent_model} \
  --output_dir ${scierc_rel_model}


I don't want it to run the full training and testing and evaluating, that would take hours. I just want to input an unlabelled dataset and for the model to predict the relations from the dataset. If it's not too much trouble, could you be as explicit and clear as to how to accomplish this? Thank you very much.

**Comment by a3616001** [comment]
Yes you can use the command as you provided. One argument missing is `--entity_output_dir`, which is the output directory of the entity model. The prediction files (`ent_pred_test.json` in this case) of the entity model should be in this directory. You need to first run the entity model to predict entities in your documents first.
