### ISSUE TITLE
Question regarding Table 4 in the paper

### ISSUE THREAD

**Issue by jzhang38** [princeton-nlp/PURE#34]
Hi,

Thanks for your excellent work!

May I ask why is the F1 score 64.2 reported in Table 4 for the "TypedMarkers" different from the 66.7 reported in Table 1 under single-sentence and Bert base settings?

Peiyuan

**Comment by a3616001** [comment]
Hi Peiyuan,

They are different because table 1 is based on the test set while table 4 is based on the development set.


Best,
Zexuan
