### ISSUE TITLE
Expired certificate for nlp.cs.princeton.edu

### ISSUE THREAD

**Issue by serenalotreck** [princeton-nlp/PURE#38]
When trying to download pretrained models with wget, I get the following error:

```
Resolving nlp.cs.princeton.edu (nlp.cs.princeton.edu)... 128.112.136.61
Connecting to nlp.cs.princeton.edu (nlp.cs.princeton.edu)|128.112.136.61|:443... connected.
ERROR: cannot verify nlp.cs.princeton.edu's certificate, issued by ‘/C=US/O=Let's Encrypt/CN=R3’:
  Issued certificate has expired.
To connect to nlp.cs.princeton.edu insecurely, use `--no-check-certificate'.
```

I was wondering if anyone else has had this problem, & if it's resolvable or if I should connect insecurely.

Thanks!

**Comment by a3616001** [comment]
Hi! I just confirmed that I can download the models with wget normally. Are you still facing this issue?
I am not sure why this happened, but if necessary, I can share the pretrained models with you through the google drive!

**Comment by serenalotreck** [comment]
I'm still getting this issue, but I think it's related to the remote server I'm working on -- when I tried to download with `wget` on my local machine, it worked. I'll try and get in touch with the folks that run the server to see if I can get it resolved, otherwise I'll send you an email for a google drive link!

Thanks!
