### ISSUE TITLE
语言

### ISSUE THREAD

**Issue by lingling1992** [princeton-nlp/PURE#39]
您好，这个模型能用在别的语言数据集上 吗

**Comment by a3616001** [comment]
您好，我们的方法是可以应用到其他的语言的；不过我们没有在其他语言的数据集上进行实验，预训练的模型无法直接用到其他语言上。

**Comment by lingling1992** [comment]
您好，我已收到您的邮件。
                         玲玲

**Comment by nlper01** [comment]
> 您好，这个模型能用在别的语言数据集上 吗

你好，请问你有在中文语料上实验过吗？

**Comment by lingling1992** [comment]
您好，我已收到您的邮件。
                         玲玲
