### ISSUE TITLE
About the "Batch Computations"

### ISSUE THREAD

**Issue by yangrui1023** [princeton-nlp/PURE#4]
Hi, Thanks for releasing the code.
I am very interested in "Batch Computations" mentioned in your paper,  but I didn‘t find out where it was implemented. 
Looking forward to your reply.

**Comment by a3616001** [comment]
Hi, thanks for your interest!

The approximation relation model (w/ batch computations) is implemented in `run_relation_approx.py`, along with the [`BertForRelationApprox`](https://github.com/princeton-nlp/PURE/blob/8517005d947afedcbb2b04df9d8de18fa1ca9b04/relation/models.py#L67) class in `relation/models.py`.

To implement this, we need to construct a 2D attention matrix (in size `seq_length * seq_length`), which can be found in this [code](https://github.com/princeton-nlp/PURE/blob/8517005d947afedcbb2b04df9d8de18fa1ca9b04/run_relation_approx.py#L55).

**Comment by yangrui1023** [comment]
Thanks!
