### ISSUE TITLE
Using own pretrained model from checkpoint

### ISSUE THREAD

**Issue by michaelstevenz** [princeton-nlp/PURE#42]
Hi,

so I have the problem that training using my own, further pretrained model results in very long training time. 
I tried with bert-base-uncased first which trains fairly fast. However my model has additional tokens in the added_tokens.json file of the checkpoint which results in at least 5x slower training. When I delete it, its as fast as usual. Also using the model to train a bert model with AutoModelForTokenClassification gives the same fast speed with the additional tokens. Only with this, it slows down when training the entity model. Any advice why this happens or how to speed this up?

Thank you.

**Comment by a3616001** [comment]
Hi!
How many additional tokens does your model have?
I am not sure what causes this issue. It will be helpful to identify the problem if you can show any profiling results (e.g., runtime of each component of the model) for a forward run!

**Comment by a3616001** [comment]
Closing the issue as it is not active.
