### ISSUE TITLE
Missing predicted value

### ISSUE THREAD

**Issue by aappaappoo** [princeton-nlp/PURE#45]
There are multiple identical entity types in a sentence, but the model always predicts only one. For example, the input is: 10,000 catties of oranges and 20,000 catties of apples, and the output is only: oranges --> fruits; why is this?

**Comment by a3616001** [comment]
Hi, could you please elaborate your question a bit? Do you use a pre-trained model or you have trained your own model? If you train the model, how large is your training dataset?
