### ISSUE TITLE
entity/models.py _get_input_tensors function

### ISSUE THREAD

**Issue by ngwlh-gl** [princeton-nlp/PURE#46]
Hi, I have a detailed question to ask, which has puzzled me for a long time.
A function called "_get_input_tensors" in 'models.py' under 'entity' folder.
def _get_input_tensors(self, tokens, spans, spans_ner_label):
        start2idx = []
        end2idx = []
        
        bert_tokens = []
        bert_tokens.append(self.tokenizer.cls_token)
        for token in tokens:
            start2idx.append(len(bert_tokens))
            sub_tokens = self.tokenizer.tokenize(token)
            bert_tokens += sub_tokens
            end2idx.append(len(bert_tokens)-1)
        bert_tokens.append(self.tokenizer.sep_token)

        indexed_tokens = self.tokenizer.convert_tokens_to_ids(bert_tokens)
        tokens_tensor = torch.tensor([indexed_tokens])

        bert_spans = [[start2idx[span[0]], end2idx[span[1]], span[2]] for span in spans]
        bert_spans_tensor = torch.tensor([bert_spans])

        spans_ner_label_tensor = torch.tensor([spans_ner_label])

        return tokens_tensor, bert_spans_tensor, spans_ner_label_tensor

Here, in "bert_spans = [[start2idx[span[0]], end2idx[span[1]], span[2]] for span in spans]", "spans" were created with a sentence（Does not contain left and right context). But start2idx and end2idx are got from a sentence plus left and right contexts. So, I think there are some problems with "bert_spans".(Maybe my understanding is wrong.） 
Could you explain this for me？ Thank you!

**Comment by a3616001** [comment]
Hi, thanks for the question! I think `spans` are actually created with context. Check [this code](https://github.com/princeton-nlp/PURE/blob/main/entity/utils.py#L117).

Let me know if you have further questions!

**Comment by ngwlh-gl** [comment]
> 

Oh, I missed some details. Thank you!
