### ISSUE TITLE
different F1 with the same seed

### ISSUE THREAD

**Issue by ngwlh-gl** [princeton-nlp/PURE#49]
Hi, I try to use your code with our own dataset.Every time I train, the results on the dev or test dataset are slightly different, maybe 0.1 F1, but I can't find the specific location in your code where this situation occurs. Have you ever tried to use the same seed, run more times and check whether the results are consistent? Thank you.

**Comment by ngwlh-gl** [comment]
> Hi, I try to use your code with our own dataset.Every time I train, the results on the dev or test dataset are slightly different, maybe 0.1 F1, but I can't find the specific location in your code where this situation occurs. Have you ever tried to use the same seed, run more times and check whether the results are consistent? Thank you.

Hello，I check this again. And F1 can fluctuate 2 ~ 3  %. Please check this problem if you are free. Thank you.

**Comment by a3616001** [comment]
Hi, are you training the entity model or the relation model?

I have checked this at an early stage and with the same seed, the code should be able to produce the same results with the same hardware settings and CUDA version. But it is possible that I modified some code later on, which may cause this.
