### ISSUE TITLE
About NER F1

### ISSUE THREAD

**Issue by YeDeming** [princeton-nlp/PURE#5]
Hi Zexuan,

In the evaluation in run_entity.py, you select the entites with max_span_length<=8 to compute tot_gold. Does it make the recall overestimate?

https://github.com/princeton-nlp/PURE/blob/8517005d947afedcbb2b04df9d8de18fa1ca9b04/run_entity.py#L76-L108

Best,
Deming

**Comment by a3616001** [comment]
Hi Deming,

Sorry for any confusion. `tot_gold` is actually computed when we read the dataset ([here](https://github.com/princeton-nlp/PURE/blob/main/entity/utils.py#L65)), and it should be the number of gold NER labels in the dataset.


Best,
Zexuan
