### ISSUE TITLE
[Paper] What are "gold" entity and relationship types?

### ISSUE THREAD

**Issue by yogeshchandrasekharuni** [princeton-nlp/PURE#52]
Hi, I was reading through your work and in section 3.2 under Training & Inference section, you define e* and r* to be "gold" entity and relationship types. Could you please explain or point to any literature that explains what exactly that means? Thank you!

**Comment by a3616001** [comment]
Hi! "gold entity types" means the ground-truth entity types. For example, our loss on the entity model is to minimize the negative log likelihood of the ground-truth entity label.

**Comment by yogeshchandrasekharuni** [comment]
Thank you for clarifying!
