### ISSUE TITLE
How to load models into Python

### ISSUE THREAD

**Issue by serenalotreck** [princeton-nlp/PURE#55]
I'd like to be able to load the model into Python so I can look at things like the model's vocabulary, and I'd like to know how I can do this.

I thought at first that I could use AllenNLP, since you use `allennlp` commands in your code. However, since the models are just zip files, and not tarfiles, [this fails](https://github.com/allenai/allennlp/issues/5718).

I then tried using `torch.load()`, but it expects a pickle, not a file.

How can I load the models into Python?

Thanks!

**Comment by a3616001** [comment]
Hi, our models are not saved in the allennlp format. 
Instead, you could use our own class to load models(implemented in [/relation/models.py](https://github.com/princeton-nlp/PURE/blob/main/relation/models.py)).

For example, `model = RelationModel.from_pretrained(output_dir, num_rel_labels=num_labels)`, where `output_dir` is the model directory and `num_labels` is the number of relation labels. Check [this line](https://github.com/princeton-nlp/PURE/blob/main/run_relation.py#L463) for reference.

**Comment by serenalotreck** [comment]
Awesome, thank you so much!
