### ISSUE TITLE
some code problems reguarding run_relation_approx(get_features_from_file)

### ISSUE THREAD

**Issue by Xeisenperg** [princeton-nlp/PURE#56]
Q1: 
after inserting context to the sentence and tokenizing the sentence, there is a line asserting the length of tokenized sentence is smaller than max sequence length (line: 154), but there is no truncation. So how could the code run through ? I just did a slice( len(tokens[:max_seq_length-4]) < max sequence length ) to make sure the code run throuhg?

Q2:  
in line 179  if (len(tokens) + 4 > max_seq_length) or (not(batch_computation) and len(tokens) > num_tokens):
it seems that it cannot satisfy any of the conditions with provided parametere (max_seq_length:128)

looking forward to your answers, and thanks in advance

**Comment by kizunasunhy** [comment]
Seems like
Q1: max_seq_length is set after observing the data distribution, so the truncation is omitted.
Q2: (len(tokens) + 4 > max_seq_length) will never be satisfied so here maybe it's redundant but the latter one will be satisfied for `N*(N-1)-1` times where `N` is the number of entities, so after the last iteration we should append to  `features` once again. I guess this is what's happening here.

**Comment by Xeisenperg** [comment]
Thanks for your insights and answers, many many thx
