### ISSUE TITLE
Approximation Model Training & Inference

### ISSUE THREAD

**Issue by kizunasunhy** [princeton-nlp/PURE#58]
Hello. Don't know if I get it right but for approximation model, why the training phase is different from the inference phase? For training phase, seems like literally it just uses one pair of entity for one instance while for inference it will list all the possible entity pairs. What's the purpose of this? And for training phase, why the `label`'s length is padded to `max_seq_length // 4`?
Thank you.

**Comment by a3616001** [comment]
Hi, during training, we didn't group up entity pairs into one instance, because we empirically found the performance would be slightly worse. We suspect this is because we actually use a larger batch size during training if we use multiple pairs.
