### ISSUE TITLE
Fine-tunning time (training time) for entity model

### ISSUE THREAD

**Issue by pauloamed** [princeton-nlp/PURE#9]
Hey! First of all, congratulations on the paper and thanks for releasing the code.

I couldn't find the time spent on the training phase (as well as the processors used) on the paper. Could you provide this info, please?

Also, have you tried your model on a distillated BERT?

Thanks!

**Comment by a3616001** [comment]
Hi! Thanks for your interest!
Training a BERT-base entity model on the ACE05 dataset takes ~6 hours on a single 2080Ti GPU.
We didn't train a model based on the distillated BERT, but generally there shouldn't be an issue to use another base encoder.
